#include "cropsim/generators/generic_crop_generator.hpp"
#include "cropsim/generators/modifier_field.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <string>
#include <yaml-cpp/yaml.h>

namespace cropsim::generators { namespace {
constexpr double pi=3.14159265358979323846; constexpr std::size_t max_rejections=10000U;
struct Distribution{double mean,minimum,maximum,stddev;bool fixed;};
enum class Operation{relative,add,replace};
struct Binding{std::size_t field;Operation operation;double strength,offset;};
struct Parameter{Distribution base;std::vector<Binding> bindings;bool clamped{};double low{},high{};std::string name;};
Distribution distribution(const YAML::Node&n,const char*name,double mean,double low,double high,double sd){if(!n)return{mean,low,high,sd,low==high};if(n.IsScalar()){const auto v=n.as<double>();if(!std::isfinite(v))throw std::invalid_argument(std::string(name)+" must be finite");return{v,v,v,0,true};}if(!n.IsMap())throw std::invalid_argument(std::string(name)+" must be a scalar or map");const auto m=n["mean"]?n["mean"].as<double>():mean,lo=n["min"]?n["min"].as<double>():low,hi=n["max"]?n["max"].as<double>():high,s=n["stddev"]?n["stddev"].as<double>():(hi-lo)/6;if(!std::isfinite(m+lo+hi+s)||lo>hi||m<lo||m>hi||s<0||(s==0&&lo!=hi))throw std::invalid_argument("invalid distribution: "+std::string(name));return{m,lo,hi,s,lo==hi};}
Parameter parameter(const YAML::Node&p,const char*name,double mean,double low,double high,double sd,const ModifierFieldSet*fields){const auto n=p[name];Parameter r{{},{},false,0,0,name};if(n&&n.IsMap()&&(n["base"]||n["modifiers"]||n["clamp"])){const auto base=n["base"]?n["base"]:n;r.base=distribution(base,name,mean,low,high,sd);if(n["modifiers"]){if(!fields||!n["modifiers"].IsSequence())throw std::invalid_argument(std::string(name)+" modifiers require modifier_fields and a sequence");for(const auto&i:n["modifiers"]){if(!i["field"]||!i["operation"]||!i["strength"])throw std::invalid_argument("invalid modifier binding for "+std::string(name));const auto op_name=i["operation"].as<std::string>();Operation op;if(op_name=="relative")op=Operation::relative;else if(op_name=="add")op=Operation::add;else if(op_name=="replace")op=Operation::replace;else throw std::invalid_argument("unknown modifier operation: "+op_name);const auto strength=i["strength"].as<double>(),offset=i["offset"]?i["offset"].as<double>():0;if(!std::isfinite(strength+offset))throw std::invalid_argument("modifier binding must be finite");r.bindings.push_back({fields->resolve(i["field"].as<std::string>()),op,strength,offset});}if(base.IsMap()&&base["min"]&&base["max"]){r.low=r.base.minimum;r.high=r.base.maximum;r.clamped=true;}}if(n["clamp"]){const auto c=n["clamp"];if(!c.IsSequence()||c.size()!=2)throw std::invalid_argument(std::string(name)+" clamp must contain two values");r.low=c[0].as<double>();r.high=c[1].as<double>();if(!std::isfinite(r.low+r.high)||r.low>r.high)throw std::invalid_argument("invalid clamp for "+std::string(name));r.clamped=true;}}else r.base=distribution(n,name,mean,low,high,sd);return r;}
double sample(const Distribution&d,MorphologyContext&r){if(d.fixed)return d.mean;for(std::size_t i=0;i<max_rejections;++i){const auto v=d.mean+d.stddev*std::sqrt(-2*std::log(r.uniform_open()))*std::cos(2*pi*r.uniform_open());if(v>=d.minimum&&v<=d.maximum)return v;}throw std::runtime_error("truncated Gaussian sampling exhausted after 10000 rejections");}
double apply(const Parameter&p,MorphologyContext&r,const std::vector<double>&values,Point2 position){auto v=sample(p.base,r);for(const auto&b:p.bindings){const auto signal=values.at(b.field);if(b.operation==Operation::relative)v*=1+b.strength*signal;else if(b.operation==Operation::add)v+=b.strength*signal;else v=b.offset+b.strength*signal;}if(p.clamped)v=std::clamp(v,p.low,p.high);if(!std::isfinite(v))throw std::runtime_error("non-finite modifier result for "+p.name+" at ("+std::to_string(position.x)+", "+std::to_string(position.y)+")");return v;}
}
struct GenericCropGenerator::Configuration{Parameter count,length,width,offset,orientation,scale;};
void GenericCropGenerator::configure(const YAML::Node&n,const ModifierFieldSet*f){auto c=std::make_shared<Configuration>(Configuration{parameter(n,"leaf_num",4,1,10,1.5,f),parameter(n,"leaf_length",1,.8,1.2,.0666667,f),parameter(n,"leaf_width",.4,.2,.6,.0666667,f),parameter(n,"leaf_offset",0,-.05,.05,.0166667,f),parameter(n,"leaf_orientation",0,-.5,.5,.1666667,f),parameter(n,"scale",.05,.05,.05,0,f)});if(c->scale.base.minimum<=0||c->count.base.minimum<1||c->length.base.minimum<=0||c->width.base.minimum<=0||c->length.base.minimum+c->offset.base.minimum<0)throw std::invalid_argument("invalid generic crop parameters");configuration_=std::move(c);}
std::vector<EllipseLeaf> GenericCropGenerator::generate(const YAML::Node&n,MorphologyContext&r)const{GenericCropGenerator g;g.configure(n,nullptr);std::vector<double>v;Context c{{},r,v};return g.generate(c);}
std::vector<EllipseLeaf> GenericCropGenerator::generate(Context&x)const{if(!configuration_)throw std::logic_error("generic crop generator is not configured");const auto&c=*configuration_;const auto count_value=apply(c.count,x.random,x.modifiers,x.position);if(count_value>static_cast<double>(std::numeric_limits<std::size_t>::max()))throw std::overflow_error("generic crop leaf count overflow");const auto count=static_cast<std::size_t>(std::llround(count_value));if(count==0)throw std::invalid_argument("generic crop leaf_num is invalid at crop position");const auto scale=apply(c.scale,x.random,x.modifiers,x.position);if(!(scale>0))throw std::invalid_argument("generic crop scale is invalid at crop position");std::vector<EllipseLeaf>out;out.reserve(count);for(std::size_t i=0;i<count;++i){const auto length=apply(c.length,x.random,x.modifiers,x.position),width=apply(c.width,x.random,x.modifiers,x.position),offset=apply(c.offset,x.random,x.modifiers,x.position),orientation=apply(c.orientation,x.random,x.modifiers,x.position);if(!(length>0&&width>0&&length+offset>=0))throw std::invalid_argument("generic crop leaf parameter is invalid at crop position");const auto theta=2*pi*static_cast<double>(i)/static_cast<double>(count)+orientation,distance=scale*(length+offset);out.push_back({distance*std::cos(theta),distance*std::sin(theta),scale*length,scale*width,theta});}return out;}
} // namespace cropsim::generators
